/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;

import java.text.DateFormat;
import java.time.Duration;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Customer_login_Success extends javax.swing.JFrame {

    /**
     * Creates new form Customer_login_Success
     */
    public Customer_login_Success() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jc1 = new javax.swing.JComboBox<>();
        jc2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        d2 = new com.toedter.calendar.JDateChooser();
        d1 = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jc4 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta2 = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();
        t11 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Customer_Page");
        setMinimumSize(new java.awt.Dimension(810, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Book Room");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(290, 10, 150, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 51));
        jLabel10.setText("Manager Name");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(150, 100, 160, 22);

        jc1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jc1.setForeground(new java.awt.Color(0, 0, 255));
        jc1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delhi", "Chandigarh", "Banglore", "Jaipur", "Mumbai", "Kolkata", "Patna", "Gurgaon", "Manali" }));
        jPanel1.add(jc1);
        jc1.setBounds(290, 140, 180, 28);

        jc2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jc2.setForeground(new java.awt.Color(0, 0, 255));
        jc2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple", "Quad", "Queen", "King", "Double Double", "Studio", "Mini Suite", "Master Suite", "Deluxe Suite", "Platinum Suite", "Extra Deluxe Suite" }));
        jPanel1.add(jc2);
        jc2.setBounds(600, 140, 160, 28);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 51));
        jLabel11.setText("Location");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(200, 140, 90, 22);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 0, 51));
        jLabel12.setText("Room Number");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(240, 220, 150, 22);

        t2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        jPanel1.add(t2);
        t2.setBounds(320, 100, 250, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 0, 51));
        jLabel19.setText("To");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(460, 180, 30, 30);

        ta1.setEditable(false);
        ta1.setColumns(20);
        ta1.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        ta1.setRows(5);
        ta1.setText("Order Details:\n");
        jScrollPane1.setViewportView(ta1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 360, 760, 120);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 255));
        jButton2.setText("Confirm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(310, 310, 130, 31);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(160, 310, 130, 31);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 0, 51));
        jLabel20.setText("Room Type");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(490, 140, 110, 30);

        t1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        jPanel1.add(t1);
        t1.setBounds(320, 60, 250, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 0, 51));
        jLabel22.setText("From");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(220, 180, 50, 30);

        d2.setMinSelectableDate(new java.util.Date(new java.util.Date().getTime() + 86400000));
        jPanel1.add(d2);
        d2.setBounds(510, 180, 140, 30);

        d1.setMinSelectableDate(new java.util.Date());
        jPanel1.add(d1);
        d1.setBounds(290, 180, 140, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 0, 51));
        jLabel13.setText("Cost for 1 day");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(420, 260, 140, 22);

        t3.setEditable(false);
        t3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        jPanel1.add(t3);
        t3.setBounds(260, 260, 130, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 51));
        jLabel14.setText("Customer Name");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(150, 60, 160, 22);
        jPanel1.add(t4);
        t4.setBounds(390, 220, 130, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 255));
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(470, 310, 130, 31);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 0, 51));
        jLabel21.setText("Total Cost");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(150, 260, 110, 22);

        t8.setEditable(false);
        t8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t8ActionPerformed(evt);
            }
        });
        jPanel1.add(t8);
        t8.setBounds(570, 260, 130, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/photo-1596386461350-326ccb383e9f.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 780, 490);

        jTabbedPane1.addTab("Book Room", jPanel1);

        jPanel3.setLayout(null);

        jc4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jc4.setForeground(new java.awt.Color(0, 0, 255));
        jc4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delhi", "Chandigarh", "Banglore", "Jaipur", "Mumbai", "Kolkata", "Patna", "Gurgaon", "Manali" }));
        jPanel3.add(jc4);
        jc4.setBounds(300, 150, 180, 28);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Feedback");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(290, 20, 120, 30);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 0, 51));
        jLabel27.setText("Name");
        jPanel3.add(jLabel27);
        jLabel27.setBounds(210, 100, 70, 22);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 0, 51));
        jLabel28.setText("Location");
        jPanel3.add(jLabel28);
        jLabel28.setBounds(190, 150, 90, 22);

        ta2.setColumns(20);
        ta2.setRows(5);
        jScrollPane2.setViewportView(ta2);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(300, 200, 360, 100);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 0, 51));
        jLabel29.setText("Feedback");
        jPanel3.add(jLabel29);
        jLabel29.setBounds(180, 210, 100, 22);

        t11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t11ActionPerformed(evt);
            }
        });
        jPanel3.add(t11);
        t11.setBounds(300, 100, 250, 30);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 255));
        jButton6.setText("Submit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(300, 330, 130, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/photo-1596386461350-326ccb383e9f.jpg"))); // NOI18N
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, 0, 770, 490);

        jTabbedPane1.addTab("Feedback", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 60, 780, 520);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 51, 204));
        jButton5.setText("<<");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(10, 10, 80, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/photo-1596386461350-326ccb383e9f.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String name = t11.getText();
        String loc = jc4.getItemAt(jc4.getSelectedIndex());
        String feed = ta2.getText();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel_management", "root", "");
            PreparedStatement ps = con.prepareStatement("Insert into feedback values(?,?,?)");
            ps.setString(1, loc);
            ps.setString(2, name);
            ps.setString(3, feed);  
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Thankyou for your valuable feedback.\nWe look forward to serve you again.");
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this,"Try After Some time","Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void t11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t11ActionPerformed

    private void t8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "Are You Sure you want to cancel?","Confirm Registration",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(result==JOptionPane.YES_OPTION){
            ta1.setText("");
            t1.setText("");
            t2.setText("");
            t3.setText("");
            t4.setText("");
            jc1.setSelectedIndex(0);
            jc2.setSelectedIndex(0);
            d1.setDate(null);
            d2.setDate(null);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String cust_name = t1.getText();
        String man_name = t2.getText();
        String loc = jc1.getItemAt(jc1.getSelectedIndex());
        String type = jc2.getItemAt(jc2.getSelectedIndex());
        String from = DateFormat.getDateInstance().format(d1.getDate());
        String to = DateFormat.getDateInstance().format(d2.getDate());
        int cost = 0;
        LocalDateTime from1 = LocalDateTime.ofInstant(d1.getDate().toInstant(), ZoneId.systemDefault());
        LocalDateTime to1 = LocalDateTime.ofInstant(d2.getDate().toInstant(), ZoneId.systemDefault());
        Duration d = Duration.between(from1, to1);
        int diff = ((int)d.toDays());
        int idx = jc2.getSelectedIndex();
        String number = t4.getText();
        String amenities = "";
        switch (idx) {
            case 0:
                amenities = "Attached Bath with necesseties such as laundry,bath products, 1 Single Bed";
                cost = 1500;
                break;
            case 1:
                amenities = "Attached Bath with necesseties such as laundry,bath products,1 HD TV, 1 Double Bed";
                cost = 2500;
                break;
            case 2:
                amenities = "Attached Bath with necesseties such as laundry,bath products,1 HD TV,1 Refrigerator, 1 Single Bed, 1 Double Bed";
                cost = 3500;
                break;
            case 3:
                amenities = "Attached Bath with necesseties such as laundry,bath products,1 HD TV,1 Refrigerator, 1 Time meal, 2 Double Bed";
                cost = 4500;
                break;
            case 4:
                amenities = "Attached Bath with necesseties such as laundry,bath products,1 HD TV,1 Refrigerator, 2 Time meal, 1 Queen Size Bed";
                cost = 5000;
                break;
            case 5:
                amenities = "Attached Bath with necesseties such as laundry,bath products,1 HD TV,1 Refrigerator, 3 Time meal, 1 King Size Bed";
                cost = 5500;
                break;
            case 6:
                amenities = "Attached Bath with necesseties such as laundry,bath products,1 HD TV, 2 Single Beds";
                cost = 2500;
                break;
            case 7:
                amenities = "Attached Bath with necesseties such as laundry,bath products,1 HD TV,1 Refrigerator, 2 Time meal, 2 Queen Size Beds";
                cost = 5500;
                break;
            case 8:
                amenities = "Attached Bath with necesseties such as laundry,bath products,1 HD TV,1 Refrigerator, 3 Time meal, 1 King Size Bed and 1 couch";
                cost = 6000;
                break;
            case 9:
                amenities = "Attached Bath with necesseties such as laundry,bath products,1 HD TV,1 Refrigerator, 3 Time meal,seperate work space, 1 master bedroom, 1 Queen Size Bed";
                cost = 8000;
                break;
            case 10:
                amenities = "Attached Bath with necesseties such as laundry,bath products,1 HD TV,1 Refrigerator, 3 Time meal.fully stocked kitchen,living space and work space, 1 master bedroom, 1 King Size Bed";
                cost = 10000;
                break;
            case 11:
                amenities = "Attached Bath with necesseties such as laundry,bath products,1 HD TV,1 Refrigerator, 3 Time meal.fully stocked kitchen,living space and work space,gym membership, 2 Bedrooms with king size beds";
                cost = 15000;
                break;
            case 12:
                amenities = "Attached Bath with necesseties such as laundry,bath products,1 HD TV,1 Refrigerator, 3 Time meal.fully stocked kitchen,living space and work space,gym membership, free invitation to all exclusive events, 2 Bedrooms with king size beds";
                cost = 18000;
                break;
            case 13:
                amenities = "Attached Bath with necesseties such as laundry,bath products,1 HD TV,1 Refrigerator, 3 Time meal.fully stocked kitchen,living space and work space,gym membership, free invitation to all exclusive events, 2 Bedrooms with king size beds and 1 bedroom with twin beds";
                cost = 25000;
                break;
            default:
                break;
        }
        int tcost = cost*diff;
        String txt = "Order Details:\n" + "Room Type:"+type+"\nLocation: "+loc+"\nCustomer Name: "+cust_name+"\nRoom Number: "+number+"\nFascilities: "+amenities+"\nTotal Cost: "+cost+" * "+diff+" = "+tcost+"\nBooked From: "+from+" To: "+to+"\nBooked By: "+man_name;
        String txt1 = "\nClick Confirm to Confirm Your Booking.";
        ta1.setText(txt+txt1);
        t3.setText(String.valueOf(tcost));
        t8.setText(String.valueOf(cost));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String cust_name = t1.getText();
        String man_name = t2.getText();
        String loc = jc1.getItemAt(jc1.getSelectedIndex());
        String type = jc2.getItemAt(jc2.getSelectedIndex());
        String from = DateFormat.getDateInstance().format(d1.getDate());
        String to = DateFormat.getDateInstance().format(d2.getDate());
        int cost1 = Integer.parseInt(t3.getText());
        int cost2 = Integer.parseInt(t8.getText());
        String number = t4.getText();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel_management", "root", "");
            PreparedStatement ps = con.prepareStatement("Insert into rooms values(?,?,?,?,?,?,?,?,?)");
            ps.setString(1, type);
            ps.setString(2, number);
            ps.setString(3, loc);
            ps.setString(4,man_name);
            ps.setString(5, cust_name);
            ps.setInt(6, cost1);
            ps.setString(7, from);
            ps.setString(8,to);
            ps.setInt(9, cost2);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Room Booked");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"Room Number already occupied. Try Another","Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        customer_login h = new customer_login();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_login_Success.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_login_Success.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_login_Success.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_login_Success.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_login_Success().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser d1;
    private com.toedter.calendar.JDateChooser d2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jc1;
    private javax.swing.JComboBox<String> jc2;
    private javax.swing.JComboBox<String> jc4;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t11;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t8;
    private javax.swing.JTextArea ta1;
    private javax.swing.JTextArea ta2;
    // End of variables declaration//GEN-END:variables
}
