/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Employee_login_success extends javax.swing.JFrame {

    /**
     * Creates new form Employee_login_success
     */
    
    
    public Employee_login_success() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jc1 = new javax.swing.JComboBox<>();
        jc2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        d2 = new com.toedter.calendar.JDateChooser();
        d1 = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jc3 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        d3 = new com.toedter.calendar.JDateChooser();
        jLabel24 = new javax.swing.JLabel();
        b2 = new javax.swing.JRadioButton();
        b1 = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jc4 = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jc5 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        t9 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta2 = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();
        t11 = new javax.swing.JTextField();
        b3 = new javax.swing.JRadioButton();
        b4 = new javax.swing.JRadioButton();
        jLabel30 = new javax.swing.JLabel();
        t12 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        t13 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Employee Page");
        setMinimumSize(new java.awt.Dimension(850, 650));
        getContentPane().setLayout(null);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Book Room");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(260, 10, 150, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 51));
        jLabel10.setText("Manager Name");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(150, 100, 160, 22);

        jc1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jc1.setForeground(new java.awt.Color(0, 0, 255));
        jc1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delhi", "Chandigarh", "Banglore", "Jaipur", "Mumbai", "Kolkata", "Patna", "Gurgaon", "Manali" }));
        jPanel1.add(jc1);
        jc1.setBounds(290, 140, 180, 28);

        jc2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jc2.setForeground(new java.awt.Color(0, 0, 255));
        jc2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple", "Quad", "Queen", "King", "Double Double", "Studio", "Mini Suite", "Master Suite", "Deluxe Suite", "Platinum Suite", "Extra Deluxe Suite" }));
        jPanel1.add(jc2);
        jc2.setBounds(600, 140, 160, 28);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 51));
        jLabel11.setText("Location");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(200, 140, 90, 22);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 0, 51));
        jLabel12.setText("Room Number");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(240, 220, 150, 22);

        t2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        jPanel1.add(t2);
        t2.setBounds(320, 100, 250, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 0, 51));
        jLabel19.setText("To");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(460, 180, 30, 30);

        ta1.setEditable(false);
        ta1.setColumns(20);
        ta1.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        ta1.setRows(5);
        ta1.setText("Order Details:\n");
        jScrollPane1.setViewportView(ta1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 360, 760, 120);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 255));
        jButton2.setText("Confirm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(310, 310, 130, 31);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(160, 310, 130, 31);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 0, 51));
        jLabel20.setText("Room Type");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(490, 140, 110, 30);

        t1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        jPanel1.add(t1);
        t1.setBounds(320, 60, 250, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 0, 51));
        jLabel22.setText("From");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(220, 180, 50, 30);

        d2.setMinSelectableDate(new java.util.Date(new java.util.Date().getTime() + 86400000));
        jPanel1.add(d2);
        d2.setBounds(510, 180, 140, 30);

        d1.setMinSelectableDate(new java.util.Date());
        jPanel1.add(d1);
        d1.setBounds(290, 180, 140, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 0, 51));
        jLabel13.setText("Cost for 1 day");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(420, 260, 140, 22);

        t3.setEditable(false);
        t3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        jPanel1.add(t3);
        t3.setBounds(260, 260, 130, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 51));
        jLabel14.setText("Customer Name");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(150, 60, 160, 22);
        jPanel1.add(t4);
        t4.setBounds(390, 220, 130, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 255));
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(470, 310, 130, 31);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 0, 51));
        jLabel21.setText("Total Cost");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(150, 260, 110, 22);

        t8.setEditable(false);
        t8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t8ActionPerformed(evt);
            }
        });
        jPanel1.add(t8);
        t8.setBounds(570, 260, 130, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/photo-1596386461350-326ccb383e9f.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 780, 490);

        jTabbedPane1.addTab("Book Room", jPanel1);

        jPanel2.setLayout(null);

        jc3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jc3.setForeground(new java.awt.Color(0, 0, 255));
        jc3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delhi", "Chandigarh", "Banglore", "Jaipur", "Mumbai", "Kolkata", "Patna", "Gurgaon", "Manali" }));
        jPanel2.add(jc3);
        jc3.setBounds(290, 110, 180, 28);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 0, 51));
        jLabel16.setText("Location");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(150, 110, 90, 22);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 0, 51));
        jLabel17.setText("Room Number");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(120, 160, 150, 22);

        t6.setEditable(false);
        jPanel2.add(t6);
        t6.setBounds(290, 160, 130, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 0, 51));
        jLabel15.setText("Customer Name");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(130, 70, 160, 22);

        t5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        jPanel2.add(t5);
        t5.setBounds(290, 70, 250, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("CheckIn/CheckOut");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(170, 10, 230, 30);

        d3.setMaxSelectableDate(new java.util.Date());
        d3.setMinSelectableDate(new java.util.Date());
        jPanel2.add(d3);
        d3.setBounds(280, 270, 140, 30);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 0, 51));
        jLabel24.setText("Date");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(200, 270, 50, 30);

        buttonGroup1.add(b2);
        b2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b2.setForeground(new java.awt.Color(51, 0, 255));
        b2.setText("Check Out");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel2.add(b2);
        b2.setBounds(320, 220, 140, 31);

        buttonGroup1.add(b1);
        b1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b1.setForeground(new java.awt.Color(51, 0, 255));
        b1.setText("Check In");
        jPanel2.add(b1);
        b1.setBounds(140, 220, 120, 31);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 0, 51));
        jLabel18.setText("Bill Amount");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(150, 320, 120, 22);

        t7.setEditable(false);
        t7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7ActionPerformed(evt);
            }
        });
        jPanel2.add(t7);
        t7.setBounds(280, 320, 250, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 255));
        jButton4.setText("Confirm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(260, 380, 130, 31);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/photo-1596386461350-326ccb383e9f.jpg"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 0, 780, 490);

        jTabbedPane1.addTab("Check In/Check Out", jPanel2);

        jPanel3.setLayout(null);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 0, 51));
        jLabel23.setText("Status");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(160, 80, 70, 22);

        jc4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jc4.setForeground(new java.awt.Color(0, 0, 255));
        jc4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delhi", "Chandigarh", "Banglore", "Jaipur", "Mumbai", "Kolkata", "Patna", "Gurgaon", "Manali" }));
        jc4.setEnabled(false);
        jPanel3.add(jc4);
        jc4.setBounds(290, 230, 180, 28);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 0, 51));
        jLabel25.setText("ID");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(470, 150, 40, 30);

        jc5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jc5.setForeground(new java.awt.Color(0, 0, 255));
        jc5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple", "Quad", "Queen", "King", "Double Double", "Studio", "Mini Suite", "Master Suite", "Deluxe Suite", "Platinum Suite", "Extra Deluxe Suite" }));
        jc5.setEnabled(false);
        jPanel3.add(jc5);
        jc5.setBounds(280, 150, 160, 28);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Manitainance");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(270, 20, 170, 30);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 0, 51));
        jLabel26.setText("Room Number");
        jPanel3.add(jLabel26);
        jLabel26.setBounds(130, 190, 150, 22);

        t9.setEnabled(false);
        jPanel3.add(t9);
        t9.setBounds(290, 190, 130, 30);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 0, 51));
        jLabel27.setText("Manager Name");
        jPanel3.add(jLabel27);
        jLabel27.setBounds(120, 370, 160, 22);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 0, 51));
        jLabel28.setText("Location");
        jPanel3.add(jLabel28);
        jLabel28.setBounds(170, 230, 90, 22);

        ta2.setColumns(20);
        ta2.setRows(5);
        ta2.setEnabled(false);
        jScrollPane2.setViewportView(ta2);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(290, 280, 240, 76);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 0, 51));
        jLabel29.setText("Issue:");
        jPanel3.add(jLabel29);
        jLabel29.setBounds(180, 280, 70, 22);

        t11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t11.setEnabled(false);
        t11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t11ActionPerformed(evt);
            }
        });
        jPanel3.add(t11);
        t11.setBounds(290, 370, 250, 30);

        buttonGroup2.add(b3);
        b3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b3.setForeground(new java.awt.Color(51, 0, 255));
        b3.setText("Open");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel3.add(b3);
        b3.setBounds(280, 80, 90, 31);

        buttonGroup2.add(b4);
        b4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b4.setForeground(new java.awt.Color(51, 0, 255));
        b4.setText("Close");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel3.add(b4);
        b4.setBounds(520, 80, 120, 31);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 0, 51));
        jLabel30.setText("Room Type");
        jPanel3.add(jLabel30);
        jLabel30.setBounds(150, 150, 110, 30);

        t12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t12.setEnabled(false);
        t12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t12ActionPerformed(evt);
            }
        });
        jPanel3.add(t12);
        t12.setBounds(520, 150, 230, 30);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 0, 51));
        jLabel31.setText("ID");
        jPanel3.add(jLabel31);
        jLabel31.setBounds(210, 410, 30, 30);

        t13.setEditable(false);
        t13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t13.setEnabled(false);
        t13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t13ActionPerformed(evt);
            }
        });
        jPanel3.add(t13);
        t13.setBounds(290, 410, 230, 30);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 255));
        jButton6.setText("Confirm");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(580, 410, 130, 31);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/photo-1596386461350-326ccb383e9f.jpg"))); // NOI18N
        jPanel3.add(jLabel7);
        jLabel7.setBounds(0, 0, 770, 490);

        jTabbedPane1.addTab("Maintainance Issue", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(20, 80, 780, 520);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 51, 204));
        jButton5.setText("<<");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(10, 20, 80, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/photo-1596386461350-326ccb383e9f.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 820, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Employee_login h = new Employee_login();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String cust_name = t1.getText();
        String man_name = t2.getText();
        String loc = jc1.getItemAt(jc1.getSelectedIndex());
        String type = jc2.getItemAt(jc2.getSelectedIndex());
        String from = DateFormat.getDateInstance().format(d1.getDate());
        String to = DateFormat.getDateInstance().format(d2.getDate());        
        int cost = 0;
        LocalDateTime from1 = LocalDateTime.ofInstant(d1.getDate().toInstant(), ZoneId.systemDefault());
        LocalDateTime to1 = LocalDateTime.ofInstant(d2.getDate().toInstant(), ZoneId.systemDefault());
        Duration d = Duration.between(from1, to1);
        int diff = ((int)d.toDays());      
        int idx = jc2.getSelectedIndex();
        String number = t4.getText();
        String amenities = "";
        if(idx==0){
            amenities = "Attached Bath with necesseties such as laundry,bath products, 1 Single Bed";
            cost = 1500;
        }
        else if(idx==1){
            amenities = "Attached Bath with necesseties such as laundry,bath products,1 HD TV, 1 Double Bed";
            cost = 2500;
        }
        else if(idx==2){
            amenities = "Attached Bath with necesseties such as laundry,bath products,1 HD TV,1 Refrigerator, 1 Single Bed, 1 Double Bed";
            cost = 3500;
        }
        else if(idx==3){
            amenities = "Attached Bath with necesseties such as laundry,bath products,1 HD TV,1 Refrigerator, 1 Time meal, 2 Double Bed";
            cost = 4500;
        }
        else if(idx==4){
            amenities = "Attached Bath with necesseties such as laundry,bath products,1 HD TV,1 Refrigerator, 2 Time meal, 1 Queen Size Bed";
            cost = 5000;
        }
        else if(idx==5){
            amenities = "Attached Bath with necesseties such as laundry,bath products,1 HD TV,1 Refrigerator, 3 Time meal, 1 King Size Bed";
            cost = 5500;
        }
        else if(idx==6){
            amenities = "Attached Bath with necesseties such as laundry,bath products,1 HD TV, 2 Single Beds";
            cost = 2500;
        }
        else if(idx==7){
            amenities = "Attached Bath with necesseties such as laundry,bath products,1 HD TV,1 Refrigerator, 2 Time meal, 2 Queen Size Beds";
            cost = 5500;
        }
        else if(idx==8){
            amenities = "Attached Bath with necesseties such as laundry,bath products,1 HD TV,1 Refrigerator, 3 Time meal, 1 King Size Bed and 1 couch";
            cost = 6000;
        }
        else if(idx==9){
            amenities = "Attached Bath with necesseties such as laundry,bath products,1 HD TV,1 Refrigerator, 3 Time meal,seperate work space, 1 master bedroom, 1 Queen Size Bed";
            cost = 8000;
        }
        else if(idx==10){
            amenities = "Attached Bath with necesseties such as laundry,bath products,1 HD TV,1 Refrigerator, 3 Time meal.fully stocked kitchen,living space and work space, 1 master bedroom, 1 King Size Bed";
            cost = 10000;
        }
        else if(idx==11){
            amenities = "Attached Bath with necesseties such as laundry,bath products,1 HD TV,1 Refrigerator, 3 Time meal.fully stocked kitchen,living space and work space,gym membership, 2 Bedrooms with king size beds";
            cost = 15000;
        }
        else if(idx==12){
            amenities = "Attached Bath with necesseties such as laundry,bath products,1 HD TV,1 Refrigerator, 3 Time meal.fully stocked kitchen,living space and work space,gym membership, free invitation to all exclusive events, 2 Bedrooms with king size beds";
            cost = 18000;
        }
        else if(idx==13){
            amenities = "Attached Bath with necesseties such as laundry,bath products,1 HD TV,1 Refrigerator, 3 Time meal.fully stocked kitchen,living space and work space,gym membership, free invitation to all exclusive events, 2 Bedrooms with king size beds and 1 bedroom with twin beds";
            cost = 25000;
        }
        int tcost = cost*diff;
        String txt = "\nOrder Details:\n"+"Room Type: "+type+"\nLocation: "+loc+"\nCustomer Name: "+cust_name+"\nRoom Number: "+number+"\nFascilities: "+amenities+"\nTotal Cost: "+cost+" * "+diff+" = "+tcost+"\nBooked From: "+from+" To: "+to+"\nBooked By: "+man_name;
        String txt1 = "\nClick Confirm to Confirm Your Booking.";
        ta1.setText(txt+txt1);
        t3.setText(String.valueOf(tcost));
        t8.setText(String.valueOf(cost));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String cust_name = t1.getText();
        String man_name = t2.getText();
        String loc = jc1.getItemAt(jc1.getSelectedIndex());
        String type = jc2.getItemAt(jc2.getSelectedIndex());
        String from = DateFormat.getDateInstance().format(d1.getDate());
        String to = DateFormat.getDateInstance().format(d2.getDate());        
        int cost1 = Integer.parseInt(t3.getText());
        int cost2 = Integer.parseInt(t8.getText());
        String number = t4.getText();
        try{
           Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel_management", "root", "");
            PreparedStatement ps = con.prepareStatement("Insert into rooms values(?,?,?,?,?,?,?,?,?)");
            ps.setString(1, type);
            ps.setString(2, number);
            ps.setString(3, loc);
            ps.setString(4,man_name);
            ps.setString(5, cust_name);
            ps.setInt(6, cost1);
            ps.setString(7, from);
            ps.setString(8,to);
            ps.setInt(9, cost2);
            ps.executeUpdate();            
            JOptionPane.showMessageDialog(this, "Room Booked");      
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"Room Number already occupied","Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex);           
        } 
        
         
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "Are You Sure you want to cancel?","Confirm Registration",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(result==JOptionPane.YES_OPTION){
            ta1.setText("");
            t1.setText("");
            t2.setText("");
            t3.setText("");
            t4.setText("");
            jc1.setSelectedIndex(0);
            jc2.setSelectedIndex(0);
            d1.setDate(null);
            d2.setDate(null);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void t7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String cust_name = t5.getText();
        String loc = jc3.getItemAt(jc3.getSelectedIndex());
        String from = DateFormat.getDateInstance().format(d3.getDate());
        int cost = 0;
        try{
           Class.forName("com.mysql.cj.jdbc.Driver");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel_management", "root", "");
           Statement ss = con.createStatement();
           
           if(b1.isSelected()){ 
               ResultSet rs = ss.executeQuery("Select *  from rooms "+ "where Customer_Name='"+cust_name+"' and City='"+loc+"' and From_Date='"+from+"'");
               if(rs.next()){
                   String number = rs.getString("Room_Number");                  
                   PreparedStatement ps = con.prepareStatement("Insert into room_status values(?,?,?,?,?,?)");
                   ps.setString(1, cust_name);            
                   ps.setString(2, loc);
                   ps.setString(3,number);
                   ps.setString(4, from);
                   ps.setString(5, "");
                   ps.setInt(6, cost);
                   ps.executeUpdate(); 
                   t6.setText(number);
                   JOptionPane.showMessageDialog(this, "Check-In successful");
               }
               else{
                   JOptionPane.showMessageDialog(this,"Please Book Room First","Error", JOptionPane.ERROR_MESSAGE);
               }
           }
           else if(b2.isSelected()){
               int cost0 = 0;
               ResultSet rs = ss.executeQuery("Select *  from rooms "+ "where Customer_Name='"+cust_name+"' and City='"+loc+"'");
               if(rs.next()){
                   cost0 = rs.getInt("cost1");
               }
               ResultSet rs1 = ss.executeQuery("Select *  from room_status "+ "where Customer_Name='"+cust_name+"' and Location='"+loc+"'");
               if(rs1.next()){
                   String number = rs1.getString("Room_Number");
                   String to = rs1.getString("checkin");                   
                   Date date1=new SimpleDateFormat("MMM d, y").parse(to);                  
                   LocalDateTime from1 = LocalDateTime.ofInstant(date1.toInstant(), ZoneId.systemDefault());                   
                   LocalDateTime to1 = LocalDateTime.ofInstant(d3.getDate().toInstant(), ZoneId.systemDefault());                   
                   Duration d = Duration.between(from1, to1);                   
                   int diff = ((int)d.toDays());          
                   int amount = cost0*diff;
                   
                   t6.setText(number);
                   t7.setText(String.valueOf(amount));
                   
                   PreparedStatement ps = con.prepareStatement("Update room_status set checkout = ?, Amount = ? where Room_number = ?");
                   ps.setString(1, from);
                   ps.setInt(2, amount);
                   ps.setString(3, number);
                   ps.executeUpdate();
                   PreparedStatement ps1 = con.prepareStatement("Delete from rooms where Room_number = ? and City = ? and Customer_Name = ?");
                   ps1.setString(1, number);
                   ps1.setString(2, loc);
                   ps1.setString(3, cust_name);
                   ps.executeUpdate(); 
                   JOptionPane.showMessageDialog(this, "Check-Out successful. Visit Again");
               }
               else{
                   JOptionPane.showMessageDialog(this,"No Check In found","Error", JOptionPane.ERROR_MESSAGE);
               }
           }
           else{
               JOptionPane.showMessageDialog(this,"Please Check event","Error", JOptionPane.ERROR_MESSAGE);
           }
               
                 
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"Try After Some Time","Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex);           
        } 
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void t8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t8ActionPerformed

    private void t11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t11ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        jc5.setEnabled(false);
        jc4.setEnabled(false);
        t9.setEnabled(false);
        ta2.setEnabled(false);
        t11.setEnabled(false); 
        t12.setEnabled(true);
        t13.setEnabled(false);
    }//GEN-LAST:event_b4ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        
            jc5.setEnabled(true);
            jc4.setEnabled(true);
            t9.setEnabled(true);
            ta2.setEnabled(true);
            t11.setEnabled(true);  
            t12.setEnabled(false);
            t13.setEnabled(true);
        
    }//GEN-LAST:event_b3ActionPerformed

    private void t12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t12ActionPerformed

    private void t13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t13ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try{
           Class.forName("com.mysql.cj.jdbc.Driver");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel_management", "root", "");
           if(b3.isSelected()){
               String type = jc5.getItemAt(jc5.getSelectedIndex());
               String loc = jc4.getItemAt(jc4.getSelectedIndex());
               String number = t9.getText();
               String issue = ta2.getText();
               String man_name = t11.getText();
               int id1 =(int)(Math.random()*(9999-1000+1)+1000);
               PreparedStatement ps = con.prepareStatement("Insert into maintain values(?,?,?,?,?,?,?)");
               ps.setInt(1, id1);
               ps.setString(2, type);
               ps.setString(3, number);
               ps.setString(4, loc);
               ps.setString(5,issue);
               ps.setString(6, "Pending");
               ps.setString(7, man_name); 
               ps.executeUpdate();            
               JOptionPane.showMessageDialog(this, "Complaint Filed. Kindly note Id for future reference");  
               t13.setText(String.valueOf(id1));
           }
           else if(b4.isSelected()){
               int id = Integer.parseInt(t12.getText());
               Statement ss = con.createStatement();
               ResultSet rs = ss.executeQuery("Select *  from maintain "+ "where ID='"+id+"'");
               if(rs.next()){
                   String type = rs.getString("Room_type");
                   String number = rs.getString("Room_Number");
                   String loc = rs.getString("City");               
                   String issue = rs.getString("Issue");
                   String man_name = rs.getString("Manager");
                   String txt = "\nID: "+id+"\nRoom Type: "+type+"\nRoom Number: "+number+"\nCity: "+loc+"\nIssue: "+issue+"\nManager Name: "+man_name;
                   int result = JOptionPane.showConfirmDialog(this, txt+"\nClick Yes to confirm", "Confirm", JOptionPane.YES_NO_OPTION);
                   if(result==JOptionPane.YES_OPTION){
                       PreparedStatement ps = con.prepareStatement("Update maintain set Status = ? where ID = ?");
                       ps.setString(1, "Close");
                       ps.setInt(2, id);
                       ps.executeUpdate();
                       JOptionPane.showMessageDialog(this, "Status Updated");
                   }
               }
               else{
                   JOptionPane.showMessageDialog(this,"No such ID exists","Error", JOptionPane.ERROR_MESSAGE);
               }
               
           }
          
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"Try After Some time","Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex);           
        } 
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee_login_success.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee_login_success.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee_login_success.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee_login_success.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee_login_success().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton b1;
    private javax.swing.JRadioButton b2;
    private javax.swing.JRadioButton b3;
    private javax.swing.JRadioButton b4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private com.toedter.calendar.JDateChooser d1;
    private com.toedter.calendar.JDateChooser d2;
    private com.toedter.calendar.JDateChooser d3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jc1;
    private javax.swing.JComboBox<String> jc2;
    private javax.swing.JComboBox<String> jc3;
    private javax.swing.JComboBox<String> jc4;
    private javax.swing.JComboBox<String> jc5;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t11;
    private javax.swing.JTextField t12;
    private javax.swing.JTextField t13;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    private javax.swing.JTextArea ta1;
    private javax.swing.JTextArea ta2;
    // End of variables declaration//GEN-END:variables
}
