/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Manage_employees extends javax.swing.JFrame {

    /**
     * Creates new form Manage_employees
     */
    public Manage_employees() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton11 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        b3 = new javax.swing.JRadioButton();
        b5 = new javax.swing.JRadioButton();
        b2 = new javax.swing.JRadioButton();
        b1 = new javax.swing.JRadioButton();
        b4 = new javax.swing.JRadioButton();
        jButton9 = new javax.swing.JButton();
        d1 = new com.toedter.calendar.JDateChooser();
        jc1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jc2 = new javax.swing.JComboBox<>();
        jButton10 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        t9 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jc3 = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        t10 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table3 = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        t11 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Empolyees");
        setMinimumSize(new java.awt.Dimension(830, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton11.setForeground(new java.awt.Color(0, 51, 204));
        jButton11.setText("<<");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(10, 10, 80, 40);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setText("Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 50, 60, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 51));
        jLabel5.setText("Email");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 90, 60, 22);

        t2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(t2);
        t2.setBounds(150, 90, 230, 28);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 51));
        jLabel7.setText("Address");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 140, 80, 22);

        t4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(t4);
        t4.setBounds(150, 180, 230, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 51));
        jLabel8.setText("DOB");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(440, 50, 50, 22);

        t3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(t3);
        t3.setBounds(150, 140, 230, 28);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 51));
        jLabel9.setText("Phone");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(60, 190, 60, 22);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 51));
        jLabel10.setText("Location");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(410, 190, 90, 22);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 51));
        jLabel11.setText("Gender");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(60, 240, 70, 22);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 0, 51));
        jLabel12.setText("Marital Status");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(60, 280, 140, 22);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 0, 51));
        jLabel13.setText("Job Title");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(410, 100, 80, 22);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 51));
        jLabel14.setText("ID No.");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(430, 140, 60, 22);

        t1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(t1);
        t1.setBounds(150, 50, 230, 30);

        t6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(t6);
        t6.setBounds(500, 90, 230, 30);

        t7.setEditable(false);
        t7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(t7);
        t7.setBounds(500, 140, 230, 30);

        buttonGroup1.add(b3);
        b3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b3.setForeground(new java.awt.Color(102, 0, 51));
        b3.setText("Other");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel1.add(b3);
        b3.setBounds(350, 240, 80, 23);

        buttonGroup2.add(b5);
        b5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b5.setForeground(new java.awt.Color(102, 0, 51));
        b5.setText("Married");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel1.add(b5);
        b5.setBounds(210, 320, 90, 23);

        buttonGroup1.add(b2);
        b2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b2.setForeground(new java.awt.Color(102, 0, 51));
        b2.setText("Female");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2);
        b2.setBounds(240, 240, 90, 23);

        buttonGroup1.add(b1);
        b1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b1.setForeground(new java.awt.Color(102, 0, 51));
        b1.setText("Male");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);
        b1.setBounds(150, 240, 70, 23);

        buttonGroup2.add(b4);
        b4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b4.setForeground(new java.awt.Color(102, 0, 51));
        b4.setText("Single");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel1.add(b4);
        b4.setBounds(210, 280, 90, 23);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 51, 204));
        jButton9.setText("Add");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(300, 400, 100, 40);
        jPanel1.add(d1);
        d1.setBounds(500, 50, 230, 30);

        jc1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jc1.setForeground(new java.awt.Color(0, 0, 255));
        jc1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delhi", "Chandigarh", "Banglore", "Jaipur", "Mumbai", "Kolkata", "Patna", "Gurgaon", "Manali" }));
        jPanel1.add(jc1);
        jc1.setBounds(500, 190, 180, 28);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/photo-1596386461350-326ccb383e9f.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 790, 480);

        jTabbedPane1.addTab("Add Employee", jPanel1);

        jPanel3.setLayout(null);

        table1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        table1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Email", "Address", "Phone", "DOB", "Job", "Id", "Location", "Gender", "Marital Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1.setGridColor(new java.awt.Color(255, 51, 51));
        table1.setName(""); // NOI18N
        table1.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        table1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table1.setShowGrid(false);
        jScrollPane2.setViewportView(table1);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(0, 320, 780, 140);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Search Employee");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(60, 0, 320, 70);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 51));
        jLabel6.setText("Search Using");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(230, 80, 130, 30);

        t8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(t8);
        t8.setBounds(360, 130, 230, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 0, 51));
        jLabel15.setText("Value");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(280, 130, 60, 22);

        jc2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jc2.setForeground(new java.awt.Color(255, 0, 51));
        jc2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "Email", "Address", "Phone", "DOB", "Job", "Id", "Location", "Gender", "Marital_Status" }));
        jc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc2ActionPerformed(evt);
            }
        });
        jPanel3.add(jc2);
        jc2.setBounds(380, 80, 140, 30);

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 51, 204));
        jButton10.setText("Search");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10);
        jButton10.setBounds(350, 200, 140, 40);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 255));
        jLabel20.setText("Employee Details");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(10, 280, 170, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/photo-1596386461350-326ccb383e9f.jpg"))); // NOI18N
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, 0, 780, 460);

        jTabbedPane1.addTab("View Employee", jPanel3);

        jPanel2.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 255));
        jLabel17.setText("Employee Details");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(10, 280, 170, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 0, 51));
        jLabel18.setText("Employee ID");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(140, 150, 130, 22);

        t9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(t9);
        t9.setBounds(280, 150, 230, 30);

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton12.setForeground(new java.awt.Color(0, 51, 204));
        jButton12.setText("Delete");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton12);
        jButton12.setBounds(280, 210, 140, 40);

        table2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        table2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Email", "Address", "Phone", "DOB", "Job", "Id", "Location", "Gender", "Marital Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table2.setGridColor(new java.awt.Color(255, 51, 51));
        table2.setName(""); // NOI18N
        table2.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        table2.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        table2.setShowGrid(false);
        jScrollPane3.setViewportView(table2);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(0, 320, 780, 140);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 255));
        jLabel19.setText("Delete Employee");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(190, 20, 320, 70);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/photo-1596386461350-326ccb383e9f.jpg"))); // NOI18N
        jPanel2.add(jLabel16);
        jLabel16.setBounds(0, 0, 780, 470);

        jTabbedPane1.addTab("Delete Employee", jPanel2);

        jPanel4.setLayout(null);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 255));
        jLabel22.setText("Update Employee");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(60, 0, 320, 70);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 0, 51));
        jLabel23.setText("Update");
        jPanel4.add(jLabel23);
        jLabel23.setBounds(280, 80, 80, 30);

        jc3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jc3.setForeground(new java.awt.Color(255, 0, 51));
        jc3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "Email", "Address", "Phone", "DOB", "Job", "Location", "Gender", "Marital_Status" }));
        jc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc3ActionPerformed(evt);
            }
        });
        jPanel4.add(jc3);
        jc3.setBounds(380, 80, 140, 30);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 0, 51));
        jLabel24.setText("Value");
        jPanel4.add(jLabel24);
        jLabel24.setBounds(280, 130, 60, 22);

        t10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel4.add(t10);
        t10.setBounds(360, 130, 230, 30);

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton13.setForeground(new java.awt.Color(0, 51, 204));
        jButton13.setText("Update");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton13);
        jButton13.setBounds(350, 210, 140, 40);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 255));
        jLabel25.setText("Employee New Details");
        jPanel4.add(jLabel25);
        jLabel25.setBounds(10, 280, 220, 30);

        table3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        table3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Email", "Address", "Phone", "DOB", "Job", "Id", "Location", "Gender", "Marital Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table3.setGridColor(new java.awt.Color(255, 51, 51));
        table3.setName(""); // NOI18N
        table3.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        table3.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        table3.setShowGrid(false);
        jScrollPane4.setViewportView(table3);

        jPanel4.add(jScrollPane4);
        jScrollPane4.setBounds(0, 320, 780, 140);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 0, 51));
        jLabel26.setText("ID");
        jPanel4.add(jLabel26);
        jLabel26.setBounds(300, 170, 30, 22);

        t11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel4.add(t11);
        t11.setBounds(360, 170, 230, 30);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/photo-1596386461350-326ccb383e9f.jpg"))); // NOI18N
        jPanel4.add(jLabel27);
        jLabel27.setBounds(0, 0, 780, 470);

        jTabbedPane1.addTab("Update", jPanel4);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 60, 790, 500);

        jLabel21.setBackground(new java.awt.Color(255, 51, 102));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/photo-1596386461350-326ccb383e9f.jpg"))); // NOI18N
        getContentPane().add(jLabel21);
        jLabel21.setBounds(0, 0, 820, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String name,email,address,phone,dob,job,location,gender = "",status= "";
        int id1 =(int)(Math.random()*(50000-10000+1)+10000);
        String id = String.valueOf(id1);
        name = t1.getText();
        email = t2.getText();
        address = t3.getText();
        phone = t4.getText();
        dob = DateFormat.getDateInstance().format(d1.getDate());
        job = t6.getText();
        location = jc1.getItemAt(jc1.getSelectedIndex());
        if(b1.isSelected()){
            gender = "Male";
        }
        else if(b2.isSelected()){
            gender = "Female";
        }
        else if(b3.isSelected()){
            gender = "Other";
        }
        if(b4.isSelected()){
            status = "Single";
        }
        else if(b5.isSelected()){
            status = "Married";
        }
        t7.setText(id);
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel_management", "root", "");
            Statement ss = con.createStatement();
            ResultSet rs = ss.executeQuery("Select id from employee_detail");
            while(rs.next()){
                if(id.equals(rs.getString("ID"))){
                    id = String.valueOf((int)(Math.random()*(50000-10000+1)+10000));
                }
            }
            String str = "\nName: "+name+"\nEmail: "+email+"\nAddress: "+address+"\nPhone: "+phone+"\nDOB: "+dob+"\nJob: "+job+"\nID: "+id+"\nLocation:"
                    +location+ "\nGender: "+gender+"\nMarital Status: "+status;
            int result = JOptionPane.showConfirmDialog(this, "Are You Sure with following details?"+str,"Confirm Registration",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
                PreparedStatement ps = con.prepareStatement("Insert into employee_detail values(?,?,?,?,?,?,?,?,?,?)");
                ps.setString(1, name);
                ps.setString(2, email);
                ps.setString(3, address);
                ps.setString(4,phone);
                ps.setString(5, dob);
                ps.setString(6, job);
                ps.setString(7, id);
                ps.setString(8,location);
                ps.setString(9,gender);
                ps.setString(10, status);
                ps.executeUpdate();            
               JOptionPane.showMessageDialog(this, "Employee Registered");               
            }         
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"Email or Id already exist","Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex);           
        }
        
        
        
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        String field = jc2.getItemAt(jc2.getSelectedIndex());
        String value = t8.getText();
        try{
            DefaultTableModel model = new DefaultTableModel(new String[]{"Name","Email","Address","Phone","DOB","Job","Id","Location","Gender","Marital Status"}, 0);
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel_management", "root", "");
            Statement ss = con.createStatement();
            ResultSet rs = ss.executeQuery("Select *  from employee_detail where "+field+"='"+value+"'");
            int count = 0;
            while(rs.next()){
               String name,email,add,phone,dob,job,location,gender,status,id;
               name = rs.getString("Name");
               email = rs.getString("Email");
               add = rs.getString("Address");
               phone = rs.getString("Phone");
               dob = rs.getString("DOB");
               job = rs.getString("Job");
               id = rs.getString("ID");
               location = rs.getString("Location");
               gender = rs.getString("Gender");
               status = rs.getString("Marital_Status");
               model.addRow(new Object[]{name,email,add,phone,dob,job,id,location,gender,status});
               table1.setModel(model);
               count++;
            }
            if(count==0){
                JOptionPane.showMessageDialog(this, "No such record found. Try with another filter");
            }
            else{
                JOptionPane.showMessageDialog(this, count+" Records Found");
            }
          
        } catch (Exception ex) {
            System.out.println(ex);           
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        Admin_login_success a  = new Admin_login_success();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel(new String[]{"Name","Email","Address","Phone","DOB","Job","Id","Location","Gender","Marital Status"}, 0);
        String id0 = t9.getText();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel_management", "root", "");
            Statement ss = con.createStatement();
            ResultSet rs = ss.executeQuery("Select *  from employee_detail "+ "where id='"+id0+"'");
            int count = 0;
            while(rs.next()){
               String name,email,add,phone,dob,job,location,gender,status,id;
               name = rs.getString("Name");
               email = rs.getString("Email");
               add = rs.getString("Address");
               phone = rs.getString("Phone");
               dob = rs.getString("DOB");
               job = rs.getString("Job");
               id = rs.getString("ID");
               location = rs.getString("Location");
               gender = rs.getString("Gender");
               status = rs.getString("Marital_Status");
               model.addRow(new Object[]{name,email,add,phone,dob,job,id,location,gender,status});
               table2.setModel(model);
               count++;
            }
            if(count==0){
                JOptionPane.showMessageDialog(this, "No such record found. Try with another filter");
            }
            else{
                int result = JOptionPane.showConfirmDialog(this, "Are You Sure with details dispalyed in table?","Confirm Deletion",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
               if(result == JOptionPane.YES_OPTION){
                PreparedStatement ps = con.prepareStatement("Delete from employee_detail where ID = ?");
                ps.setString(1, id0);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Employee Removed");
                t9.setText(""); 
                model.setRowCount(0);
            } 
            }
            
          
        } catch (Exception ex) {
            System.out.println(ex);           
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel(new String[]{"Name","Email","Address","Phone","DOB","Job","Id","Location","Gender","Marital Status"}, 0);
        String field = jc3.getItemAt(jc3.getSelectedIndex());
        String value = t10.getText();
        String id0 = t11.getText();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel_management", "root", "");
            //Table code from here
            Statement ss = con.createStatement();
            int result = JOptionPane.showConfirmDialog(this, "Are You Sure?","Confirm updation",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
                PreparedStatement ps = con.prepareStatement("Update employee_detail set "+field+"='"+value+"' where id='"+id0+"'");
                System.out.println("Update employee_detail set "+field+"='"+value+"where id='"+id0+"'");                
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Employee Updated");
                t9.setText(""); 
                model.setRowCount(0);
            }
            ResultSet rs = ss.executeQuery("Select *  from employee_detail "+ "where id='"+id0+"'");
            int count = 0;
            while(rs.next()){
               String name,email,add,phone,dob,job,location,gender,status,id;
               name = rs.getString("Name");
               email = rs.getString("Email");
               add = rs.getString("Address");
               phone = rs.getString("Phone");
               dob = rs.getString("DOB");
               job = rs.getString("Job");
               id = rs.getString("ID");
               location = rs.getString("Location");
               gender = rs.getString("Gender");
               status = rs.getString("Marital_Status");
               model.addRow(new Object[]{name,email,add,phone,dob,job,id,location,gender,status});
               table3.setModel(model);
               count++;
            }
            if(count==0){
                JOptionPane.showMessageDialog(this, "No such record found. Try with another filter");
            }
            
          
        } catch (Exception ex) {
            System.out.println(ex);           
        }
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jc3ActionPerformed

    private void jc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jc2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_employees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton b1;
    private javax.swing.JRadioButton b2;
    private javax.swing.JRadioButton b3;
    private javax.swing.JRadioButton b4;
    private javax.swing.JRadioButton b5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private com.toedter.calendar.JDateChooser d1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jc1;
    private javax.swing.JComboBox<String> jc2;
    private javax.swing.JComboBox<String> jc3;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t10;
    private javax.swing.JTextField t11;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    private javax.swing.JTable table3;
    // End of variables declaration//GEN-END:variables
}
