/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Room_Management extends javax.swing.JFrame {

    /**
     * Creates new form Room_Management
     */
    public Room_Management() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton11 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jc1 = new javax.swing.JComboBox<>();
        jc5 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table4 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jc3 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jc4 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table3 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Room Management");
        setMinimumSize(new java.awt.Dimension(820, 590));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton11.setForeground(new java.awt.Color(0, 51, 204));
        jButton11.setText("<<");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(10, 10, 80, 40);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel1.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 51));
        jLabel10.setText("Location");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(200, 30, 90, 22);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 51, 204));
        jButton9.setText("Check");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(270, 140, 120, 40);

        jc1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jc1.setForeground(new java.awt.Color(0, 0, 255));
        jc1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delhi", "Chandigarh", "Banglore", "Jaipur", "Mumbai", "Kolkata", "Patna", "Gurgaon", "Manali" }));
        jPanel1.add(jc1);
        jc1.setBounds(300, 30, 180, 28);

        jc5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jc5.setForeground(new java.awt.Color(0, 0, 255));
        jc5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple", "Quad", "Queen", "King", "Double Double", "Studio", "Mini Suite", "Master Suite", "Deluxe Suite", "Platinum Suite", "Extra Deluxe Suite" }));
        jPanel1.add(jc5);
        jc5.setBounds(300, 80, 180, 28);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 0, 51));
        jLabel18.setText("Room Type");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(180, 80, 110, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 255));
        jLabel22.setText("Details");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(10, 190, 70, 30);

        table4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        table4.setForeground(new java.awt.Color(0, 0, 204));
        table4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Room Type", "Room Number", "City", "Manager", "Customer_Name", "Bill", "From Date", "To Date", "cost/day"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table4.setGridColor(new java.awt.Color(255, 51, 51));
        table4.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        table4.setShowGrid(false);
        table4.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(table4);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(10, 230, 760, 210);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/photo-1596386461350-326ccb383e9f.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 790, 480);

        jTabbedPane1.addTab("Check Bookings", jPanel1);

        jPanel3.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 51));
        jLabel6.setText("Location");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(220, 30, 90, 30);

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 51, 204));
        jButton10.setText("Search");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10);
        jButton10.setBounds(280, 130, 140, 40);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 255));
        jLabel20.setText("Details");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(10, 190, 70, 30);

        jc3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jc3.setForeground(new java.awt.Color(0, 0, 255));
        jc3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delhi", "Chandigarh", "Banglore", "Jaipur", "Mumbai", "Kolkata", "Patna", "Gurgaon", "Manali" }));
        jPanel3.add(jc3);
        jc3.setBounds(320, 30, 180, 28);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 0, 51));
        jLabel15.setText("Room Type");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(200, 80, 110, 30);

        jc4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jc4.setForeground(new java.awt.Color(0, 0, 255));
        jc4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple", "Quad", "Queen", "King", "Double Double", "Studio", "Mini Suite", "Master Suite", "Deluxe Suite", "Platinum Suite", "Extra Deluxe Suite" }));
        jPanel3.add(jc4);
        jc4.setBounds(320, 80, 180, 28);

        table2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        table2.setForeground(new java.awt.Color(0, 0, 204));
        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Room Type", "Room Number", "City", "Issue", "Status", "Manager"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table2.setGridColor(new java.awt.Color(255, 51, 51));
        table2.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        table2.setShowGrid(false);
        table2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(table2);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(10, 230, 760, 210);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/photo-1596386461350-326ccb383e9f.jpg"))); // NOI18N
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, 0, 780, 460);

        jTabbedPane1.addTab("Maintainence Record", jPanel3);

        jPanel2.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 255));
        jLabel19.setText("Room Details");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(210, 20, 170, 40);

        jScrollPane4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 51)));

        table3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        table3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table3.setForeground(new java.awt.Color(0, 0, 255));
        table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Single Rooms", "1500/-", "Attached bath with necessacities.", "Room", "-", "1001", "25", "1 Single Bed"},
                {"Double Rooms", "2500/-", "Single room with TV ", "Room", "-", "1002", "20", "1 Double Bed"},
                {"Triple Rooms", "3500/-", "Double room with Refrigerator", "Room", "-", "1003", "15", "1 Single and 1 Double Bed"},
                {"Quad Rooms", "4500/-", "Triple rooms with meals for 1 time", "Room", "-", "1004", "15", "2 Double bed"},
                {"Queen", "5000/-", "Quad rooms with 2 time meals", "Room", "-", "1005", "15", "1 Queen Size Bed"},
                {"King", "5500/-", "Queen rooms with 3 time meal", "Room", "-", "1006", "15", "1 King Size Bed"},
                {"Twin", "2500/-", "Double Room", "Room", "-", "1007", "15", "2 Single Beds"},
                {"Double Double", "5500/-", "Queen Room", "Room", "-", "1008", "15", "2 Queen Size Beds"},
                {"Studio", "6000/-", "King Room with coucj", "Room", "-", "1009", "10", "1 Double bed with couch"},
                {"Mini Suite", "8000/-", "King Room with additional work space", "Suite", "1 Bedroom and work space with work bench", "1010", "10", "1 Queen Size Bed"},
                {"Master Suite", "10000/-", "King Room with living space and kitchen", "Suite", "1 Bedroom and living space with sofas and fully stocked kitchen", "1011", "8", "1 King Size Bed"},
                {"Deluxe Suite", "15000/-", "Master Suite with additional gym services", "Suite", "2 adjoining/Connecting Bedrooms", "1012", "5", "2 King size beds and Living Space"},
                {"Platinum Suite", "18000/-", "Deluxe suite with invitation to exclusive events", "Suite", "2 adjoining rooms", "1013", "5", "2 King Size bed with living space and work Space"},
                {"Extra deluxe Suite", "25000/-", "Pllatinum Suite", "Suite", "3 rooms with common living space and seperate work space", "1014", "5", "2 King size beds and 2 single beds"}
            },
            new String [] {
                "Type", "Cost/day", "Amenities", "Room/Suite", "Rooms in Suite", "Room ID", "Total Rooms/hotel", "Bed Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table3.setGridColor(new java.awt.Color(255, 51, 51));
        table3.setName(""); // NOI18N
        table3.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        table3.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        table3.setShowGrid(false);
        jScrollPane4.setViewportView(table3);

        jPanel2.add(jScrollPane4);
        jScrollPane4.setBounds(0, 70, 780, 250);

        jScrollPane1.setForeground(new java.awt.Color(51, 0, 51));
        jScrollPane1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Note: \nAll the rooms include 24 hours room service and access to in house restaurants, clubs and pool area, \nhowever availability would be conditional and also charges to each would be provided to you during \ncheck ins.");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(70, 330, 660, 100);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/photo-1596386461350-326ccb383e9f.jpg"))); // NOI18N
        jPanel2.add(jLabel16);
        jLabel16.setBounds(0, 0, 780, 470);

        jTabbedPane1.addTab("Different Room Details", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 60, 790, 500);

        jLabel21.setBackground(new java.awt.Color(255, 51, 102));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/photo-1596386461350-326ccb383e9f.jpg"))); // NOI18N
        getContentPane().add(jLabel21);
        jLabel21.setBounds(0, 0, 820, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        Admin_login_success a  = new Admin_login_success();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        String loc = jc3.getItemAt(jc3.getSelectedIndex());
        String room = jc4.getItemAt(jc4.getSelectedIndex());        
        DefaultTableModel model = new DefaultTableModel(new String[]{"ID","Room Type", "Room Number","City","Issue", "Status","Manager"}, 0);
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel_management", "root", "");
            Statement ps = con.createStatement();
            ResultSet rs = ps.executeQuery("SELECT * FROM Maintain WHERE Room_Type = '"+room+"' OR City = '"+loc+"'");
           int count  = 0;           
            while(rs.next()){
               String type,number,city,issue,status1,manager;
               int id = rs.getInt("ID");
               type = rs.getString("Room_Type");
               number = rs.getString("Room_Number");
               city = rs.getString("City");
               issue = rs.getString("Issue");
               status1 = rs.getString("Status");
               manager = rs.getString("Manager");
               model.addRow(new Object[]{id,type,number,city,issue,status1,manager});
               table2.setModel(model);
               count++;
            }  
            if(count==0){
                JOptionPane.showMessageDialog(this, "No data Found");
            }
            else{
                JOptionPane.showMessageDialog(this,count + " such entries exist");
            }
            
            
        } catch (Exception ex) {
            System.out.println(ex);           
        }
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String loc = jc1.getItemAt(jc1.getSelectedIndex());
        String room = jc5.getItemAt(jc5.getSelectedIndex());
        
        DefaultTableModel model = new DefaultTableModel(new String[]{"Room Type", "Room Number","City","Manager","Customer_Name","Bill","From Date","To Date","Cost/day"}, 0);
        model.setRowCount(0);
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel_management", "root", "");
            Statement ps = con.createStatement();
            ResultSet rs = ps.executeQuery("SELECT * FROM rooms WHERE Room_Type = '"+room+"' OR City = '"+loc+"'");
           int count  = 0;           
            while(rs.next()){
               String type,number,city,manager,cust,from,to;
               int bill,cost;
               type = rs.getString("Room_Type");
               number = rs.getString("Room_Number");
               city = rs.getString("City");
               manager = rs.getString("Manager");
               cust = rs.getString("Customer_Name");
               bill = rs.getInt("Cost");
               from = rs.getString("From_Date");
               to = rs.getString("To_date");
               cost = rs.getInt("cost1");               
               model.addRow(new Object[]{type,number,city,manager,cust,bill,from,to,cost});
               table4.setModel(model);
               count++;
            }  
            if(count==0){
                JOptionPane.showMessageDialog(this, "No data Found");
            }
            else{
                JOptionPane.showMessageDialog(this,count + " such entries exist");
            }
            
            
        } catch (Exception ex) {
            System.out.println(ex);           
        }
        
        
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Room_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Room_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Room_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Room_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Room_Management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> jc1;
    private javax.swing.JComboBox<String> jc3;
    private javax.swing.JComboBox<String> jc4;
    private javax.swing.JComboBox<String> jc5;
    private javax.swing.JTable table2;
    private javax.swing.JTable table3;
    private javax.swing.JTable table4;
    // End of variables declaration//GEN-END:variables
}
